### ISSUE TITLE
Flip View for iOS

### ISSUE THREAD

**Issue by pottabathini** [gruan01/FlipView#2]
Hello Good Day,

We love this plugin and we started using in our project we able to integrate in both Android and Windows but we realized that there is not implementation available for iOS. 

Is there any chance to submit iOS code hopefully today. We are eagerly waiting for that.

I know this is not a issue but I didn't find a way to reach this to you. That is why I posted here.,

Thank you.

**Comment by gruan01** [comment]
Hi,
Actually, I don't know how to implementation it for ios. I need time to find ios' example.
Please waiting more time.

**Comment by pottabathini** [comment]
Hi Thank you for your replay. I hope you will get that done in next couple of days. Please share with us once it is done. We will wait for this.

Thank you.

**Comment by pottabathini** [comment]
Hey, we found your control to be lot lot better than another one that is based on CarouselPage and we shall spread your control if you can get the iOS done too.

Many congratulations to  you on the great work for Windows and Android.

Cheers.

**Comment by pottabathini** [comment]
Hi Again, I stuck with one issue in your project. You written code like Flipview open on first page.

We modified same code to show on second page instead of first page. But it is giving error. Please check below link for modified code of yours.

https://drive.google.com/file/d/0B3NSyNxpw3ZASF85dWZXVERrVTg/view?usp=sharing

Please check in Windows Phone and help us out. 

if that is easy to fix please share with us for both android and windows.

Thank you In advance.

**Comment by gruan01** [comment]
Hello, 
I can't open your share link, China GFW blocked it, please send email to me : gruan@asnum.com
Thanks.

**Comment by pottabathini** [comment]
I sent mail Please check and give your response.

Thank you.

**Comment by gruan01** [comment]
Hi, 
This bug has fixed, please see:
https://github.com/gruan01/FlipView/commit/5ff54f1ed421ccfe166e0ff0fff43bb2b42dfdab
Thanks

**Comment by gruan01** [comment]
Hello , this Flip for ios has been finished.

Please see detail:
https://github.com/gruan01/FlipView/commit/6c8f84f59f75fc239bc71bedb839a34cab8b8231

**Comment by pottabathini** [comment]
+1 Thank you so much for your effort, I will check.
